apiVersion: v1
kind: Namespace
metadata:
  name: userapplication

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
  namespace: userapplication
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-service-container
          image: 'user-service:1.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9096
---

apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: userapplication
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9096
  type: NodePort
